### ISSUE TITLE
Source code for OSex.pex is not in repo

### ISSUE THREAD

**Issue by johnbturnip** [acepleiades/OpenSex#108]
The defining feature of open source projects is that their source code is available.  It seems pretty strange for an open source project to not include the source code for its one and only script.

**Comment by acepleiades** [comment]
OSex.pex is an empty file. OStim checks for it in order to determine whether or not OSex is installed. I doesn't contain anything.

**Comment by johnbturnip** [comment]
Ah!  Thank you!
