### ISSUE TITLE
Inconsistencies I found so far

### ISSUE THREAD

**Issue by Valreyon** [acepleiades/OpenSex#12]
Mod versions:
- OSA v2.023-SE
- OStim v5.4
- OpenSex v0.6

I hope the scene IDs are enough.

1. OpS|Kne!LyB|VJ|LesbianKneLyBCunnilingus
Issue: all speeds stimulate the sub, even though the dom is licked

2. OpS|LyB!AFo|VHJ|AceLesbian69Fingering
Issue: only speed 0.5 stimulates both, after that only the dom is stimulated

3. OpS|Kne!LyB|Po|BreastGroping
Issue: its only speed (1) stimulates the dom, although I would assume it should stimulate the sub being fondled

I also noticed with both these animations, that the speed an animation starts with, is not the lowest. Both mentioned scene IDs start with speed 0.75, even though the lowest speed is 0.5.
I even tested some animations not from OpenSex - specifically the "Lesbian 69" from Nibbles Animation Pack for OStim - and the animation also starts at 1, even though you can slow it down one step (without a number, curiously).

EDIT: I forgot another animation I already tested, see 3.

**Comment by acepleiades** [comment]
Thank you very much for the issue report...
For LesbianKneLyBCunnilingus initially I tried to simply swap the actors in the animation, but there were scaling issues and I need to export the animations again with correct scaling for the correct actors
For AceLesbian69Fingering I'll look into what causes that problem... Sounds really weird
I'll see if there if BreastGroping can have the performing actor changed and if that fixes the issue
As for animations starting at speed 2, it's a bug within OSA. I think it's not a big problem though
I'll try to fix these issues in the current branch I'm working on

**Comment by acepleiades** [comment]
These animations are no longer part of the mod
