### ISSUE TITLE
V0.7 Female Masturbation Issue

### ISSUE THREAD

**Issue by DragoFall** [acepleiades/OpenSex#14]
Mod versions:

OSA v2.023-SE
OStim v5.4
OpenSex v0.7     

OpS|Sit!Sit|Po|AceSittingMasturbationFemale - This animation does not raise the females stimulation bar, just the doms, also if you run Ostim with clothes taken off mid scene it will un-equip the doms clothes. I did test setting <speed a="1" to 0 and that did not change anything.

**Comment by acepleiades** [comment]
I think the problem may be that the animation class, Masturbation, always stimulates the male regardless of that value...
We could try switching the animation class to something else but that requires changing the directory as well
`OpS|Sit!Sit|Po|AceSittingMasturbationFemale`
requires the xml file to be in
`OpS\SitSit\Po\`
So if we changed the animation class from Po to Sx it would need to be in
`OpS\SitSit\Sx\`
I don't know if there is a better suited animation class for us to use...
These are the ones available

![Screenshot 2022-01-19 131527](https://user-images.githubusercontent.com/69649956/150171388-a0245e09-1fd2-4908-a729-5ff10169c5fd.png)

**Comment by acepleiades** [comment]
Maybe Pf1 or Pf2 would be the correct animation class

**Comment by acepleiades** [comment]
I changed the female masturbation to this and it still stimulates the male
```
<scene id="OpS|Sit!Sit|Pf2|AceSittingMasturbationFemale" actors="2" style="OScene">
<info name="Sitting Masturbation Female" animator="Ace"/>
<region om="A" maj="K" min="K" stage="" step="" story=""/>
<anim id="0SxOpS_Po-AceSittingMasturbationFemale_S1" t="L" l="2"/>
<speed a="0" min="1" max="4" name="thrusts">
etc...
```
I'm closing to chalking it off as an OStim issue but still open for any other alternatives.

**Comment by acepleiades** [comment]
The bug has been fixed in https://github.com/acepleiades/OpenSex/pull/15
