### ISSUE TITLE
No animations / Freeze when kissing

### ISSUE THREAD

**Issue by TheDreamer21160** [acepleiades/OpenSex#54]
Good morning !

I am unable to achieve an animation sequence with the mod.

When I have to kiss my partner, the action freezes after the screen temporarily goes black.

I use the "addon version" of the mod with Oromance and i specify that I have all the prerequisites, Ostim, OSA, OSEX and the animation mods without forgetting the fact that they are installed in order of course

Do you know what is causing this and how to fix it?

Thank you !

**Comment by acepleiades** [comment]
You probably installed it incorrectly
Refer to the Nexus page, installation guide, ask for help in the support channel on Discord.
